# -*- coding: utf-8 -*-
"""PROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eUReak-81szas2bkXxAL6qlQyzrG7UmF
"""

# Step 1: Create a new directory for extraction
!mkdir extracted_data

# Step 2: Extract the ZIP file into the extracted_data folder
!unzip 1512427.zip -d extracted_data

print("Extraction complete!")

# Step 1: Create a new directory for final extraction
!mkdir final_extracted_data

# Step 2: Extract each ZIP file into the final_extracted_data folder
!unzip extracted_data/brainTumorDataPublic_1-766.zip -d final_extracted_data
!unzip extracted_data/brainTumorDataPublic_767-1532.zip -d final_extracted_data
!unzip extracted_data/brainTumorDataPublic_1533-2298.zip -d final_extracted_data
!unzip extracted_data/brainTumorDataPublic_2299-3064.zip -d final_extracted_data

print("Final extraction complete!")

!ls final_extracted_data

import cv2

class MRI(Dataset):
    def __init__(self):
        images = []
        labels = []

        # Load all .mat files
        mat_files = glob.glob("final_extracted_data/*.mat")
        print(f"Number of .mat files found: {len(mat_files)}")

        for f in mat_files:
            try:
                # Load the .mat file using h5py
                with h5py.File(f, 'r') as data:
                    # Access the 'cjdata' group
                    cjdata = data['cjdata']

                    # Extract image and label
                    img = np.array(cjdata['image'])  # Image data
                    label = np.array(cjdata['label'])  # Label data

                    # Resize image to (512, 512)
                    img = cv2.resize(img, (512, 512))

                    # Check label shape
                    if label.shape != (1, 1):
                        print(f"Skipping file {f}: Unexpected label shape {label.shape}")
                        continue

                    # Normalize the image to [0, 1]
                    img = img.astype(np.float32) / np.max(img)

                    # Add channel dimension (1, H, W) for grayscale images
                    img = np.expand_dims(img, axis=0)  # Shape: (1, 512, 512)

                    # Append to lists
                    images.append(img)
                    labels.append(label[0][0])  # Extract scalar label (e.g., 1.0 or 0.0)

            except Exception as e:
                print(f"Failed to load file {f}: {e}")

        # Convert to numpy arrays
        self.images = np.array(images, dtype=np.float32)
        self.labels = np.array(labels, dtype=np.float32)

    def __len__(self):
        return len(self.images)

    def __getitem__(self, index):
        sample = {'image': self.images[index], 'label': self.labels[index]}
        return sample

import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader
import glob
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, accuracy_score
import h5py
import torch.nn as nn
import torch.nn.functional as F
import seaborn as sns
import cv2

# Dataset Class
class MRI(Dataset):
    def __init__(self):
        images = []
        labels = []

        # Load all .mat files
        mat_files = glob.glob("final_extracted_data/*.mat")
        print(f"Number of .mat files found: {len(mat_files)}")

        for f in mat_files:
            try:
                # Load the .mat file using h5py
                with h5py.File(f, 'r') as data:
                    # Access the 'cjdata' group
                    cjdata = data['cjdata']

                    # Extract image and label
                    img = np.array(cjdata['image'])  # Image data
                    label = np.array(cjdata['label'])  # Label data

                    # Resize image to (512, 512)
                    img = cv2.resize(img, (512, 512))

                    # Check label shape
                    if label.shape != (1, 1):
                        print(f"Skipping file {f}: Unexpected label shape {label.shape}")
                        continue

                    # Normalize the image to [0, 1]
                    img = img.astype(np.float32) / np.max(img)

                    # Add channel dimension (1, H, W) for grayscale images
                    img = np.expand_dims(img, axis=0)  # Shape: (1, 512, 512)

                    # Append to lists
                    images.append(img)
                    labels.append(label[0][0])  # Extract scalar label (e.g., 1.0 or 0.0)

            except Exception as e:
                print(f"Failed to load file {f}: {e}")

        # Convert to numpy arrays
        self.images = np.array(images, dtype=np.float32)
        self.labels = np.array(labels, dtype=np.float32)

    def __len__(self):
        return len(self.images)

    def __getitem__(self, index):
        sample = {'image': self.images[index], 'label': self.labels[index]}
        return sample


# CNN Model
class CNN(nn.Module):
    def __init__(self):
        super(CNN, self).__init__()
        self.cnn_model = nn.Sequential(
            nn.Conv2d(in_channels=1, out_channels=6, kernel_size=5),  # Input channel = 1
            nn.Tanh(),
            nn.AvgPool2d(kernel_size=2, stride=5),
            nn.Conv2d(in_channels=6, out_channels=16, kernel_size=5),
            nn.Tanh(),
            nn.AvgPool2d(kernel_size=2, stride=5)
        )
        self.fc_model = nn.Sequential(
            nn.Linear(in_features=6400, out_features=120),  # Updated input size
            nn.Tanh(),
            nn.Linear(in_features=120, out_features=84),
            nn.Tanh(),
            nn.Linear(in_features=84, out_features=1)
        )

    def forward(self, x):
        x = self.cnn_model(x)
        x = x.view(x.size(0), -1)  # Flatten
        x = self.fc_model(x)
        x = F.sigmoid(x)
        return x


# Threshold Function
def threshold(scores, threshold=0.50):
    return (scores >= threshold).astype(np.float32)


# Function to Display Random Images
def plot_random_images(dataset, num=5):
    if len(dataset) == 0:
        print("Dataset is empty. Cannot display images.")
        return

    indices = np.random.choice(len(dataset), num, replace=False)
    plt.figure(figsize=(16, 9))
    for i, idx in enumerate(indices):
        sample = dataset[idx]
        img = sample['image']
        label = sample['label']

        # Reshape image to (H, W) for grayscale images
        img = img.squeeze(0)  # Remove channel dimension (1, H, W) -> (H, W)

        plt.subplot(1, num, i + 1)
        plt.title("Tumor" if label == 1 else "Healthy")
        plt.imshow(img, cmap='gray')  # Use grayscale colormap
        plt.axis('off')
    plt.show()


# Main Execution
if __name__ == "__main__":
    # Dataset
    mri_dataset = MRI()

    # Check dataset size
    print(f"Dataset size: {len(mri_dataset)}")
    if len(mri_dataset) == 0:
        raise ValueError("Dataset is empty. Please check the .mat file paths and keys.")

    # Display Random Images
    print("Displaying random images from the dataset...")
    plot_random_images(mri_dataset, num=5)

    # Device Setup
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    # Model Initialization
    model = CNN().to(device)

    # DataLoader
    dataloader = DataLoader(mri_dataset, batch_size=32, shuffle=False)

    # Evaluation
    model.eval()
    outputs = []
    y_true = []

    with torch.no_grad():
        for D in dataloader:
            image = D['image'].to(device)
            label = D['label'].to(device)

            y_hat = model(image)

            outputs.append(y_hat.cpu().detach().numpy())
            y_true.append(label.cpu().detach().numpy())

    outputs = np.concatenate(outputs, axis=0).squeeze()
    y_true = np.concatenate(y_true, axis=0).squeeze()

    # Debugging: Check unique values in y_true and outputs
    print("Unique values in y_true:", np.unique(y_true))
    print("Unique values in outputs:", np.unique(outputs))

    # Threshold predictions
    y_pred = threshold(outputs)

    # Accuracy Calculation
    print("Accuracy:", accuracy_score(y_true, y_pred))

    # Confusion Matrix
    cm = confusion_matrix(y_true, y_pred)

    # Get unique labels from y_true and predictions
    unique_labels = np.unique(np.concatenate((y_true, y_pred)))

    # Map labels to meaningful names
    label_names = ['Healthy', 'Tumor']
    if len(unique_labels) > 2:
        label_names += ['Unknown'] * (len(unique_labels) - 2)

    # Plot confusion matrix
    plt.figure(figsize=(16, 9))
    ax = plt.subplot()
    sns.heatmap(cm, annot=True, fmt='g', ax=ax, annot_kws={"size": 20})

    # Labels, Title, and Ticks
    ax.set_xlabel('Predicted labels', fontsize=20)
    ax.set_ylabel('True labels', fontsize=20)
    ax.set_title('Confusion Matrix', fontsize=20)
    ax.xaxis.set_ticklabels(label_names, fontsize=20)
    ax.yaxis.set_ticklabels(label_names, fontsize=20)

    plt.show()

import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader
import glob
import matplotlib.pyplot as plt
from sklearn.metrics import (
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
)
import h5py
import torch.nn as nn
import torch.optim as optim
import seaborn as sns
import cv2

# Dataset Class
class MRI(Dataset):
    def __init__(self):
        self.mat_files = glob.glob("final_extracted_data/*.mat")
        print(f"Number of .mat files found: {len(self.mat_files)}")

    def __len__(self):
        return len(self.mat_files)

    def __getitem__(self, index):
        try:
            # Load the .mat file using h5py
            f = self.mat_files[index]
            with h5py.File(f, 'r') as data:
                cjdata = data['cjdata']

                # Extract image and label
                img = np.array(cjdata['image'])  # Image data
                label = np.array(cjdata['label'])  # Label data

                # Resize image to (512, 512)
                img = cv2.resize(img, (512, 512))

                # Normalize the image to [0, 1]
                img = img.astype(np.float32) / np.max(img)

                # Add channel dimension (1, H, W) for grayscale images
                img = np.expand_dims(img, axis=0)  # Shape: (1, 512, 512)

                return {'image': img, 'label': label[0][0] - 1}  # Subtract 1 to make labels 0-based

        except Exception as e:
            print(f"Failed to load file {f}: {e}")
            return None


# CNN Model
class CNN(nn.Module):
    def __init__(self, num_classes=3):  # Specify number of classes
        super(CNN, self).__init__()
        self.cnn_model = nn.Sequential(
            nn.Conv2d(in_channels=1, out_channels=6, kernel_size=5),  # Input channel = 1
            nn.Tanh(),
            nn.AvgPool2d(kernel_size=2, stride=5),
            nn.Conv2d(in_channels=6, out_channels=16, kernel_size=5),
            nn.Tanh(),
            nn.AvgPool2d(kernel_size=2, stride=5)
        )
        self.fc_model = nn.Sequential(
            nn.Linear(in_features=6400, out_features=120),  # Updated input size
            nn.Tanh(),
            nn.Linear(in_features=120, out_features=84),
            nn.Tanh(),
            nn.Linear(in_features=84, out_features=num_classes)  # Output for 3 classes
        )

    def forward(self, x):
        x = self.cnn_model(x)
        x = x.view(x.size(0), -1)  # Flatten
        x = self.fc_model(x)
        return x  # Raw logits (no softmax here, handled by loss function)


# Predict Function for Multiclass
def predict_multiclass(scores):
    return np.argmax(scores, axis=1)  # Get the index of the maximum score


# Plot Confusion Matrix
def plot_confusion_matrix(y_true, y_pred, class_names, title="Confusion Matrix"):
    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='g', cmap='Blues', xticklabels=class_names, yticklabels=class_names)
    plt.title(title, fontsize=16)
    plt.xlabel("Predicted Labels", fontsize=14)
    plt.ylabel("True Labels", fontsize=14)
    plt.show()


# Main Execution
if __name__ == "__main__":
    # Dataset
    mri_dataset = MRI()

    # Check dataset size
    print(f"Dataset size: {len(mri_dataset)}")
    if len(mri_dataset) == 0:
        raise ValueError("Dataset is empty. Please check the .mat file paths and keys.")

    # DataLoader
    dataloader = DataLoader(mri_dataset, batch_size=32, shuffle=True)

    # Device Setup
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    # Model Initialization
    model = CNN(num_classes=3).to(device)

    # Loss Function and Optimizer
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=0.001)

    # Training Loop
    num_epochs = 10
    for epoch in range(num_epochs):
        model.train()
        running_loss = 0.0
        for D in dataloader:
            image = D['image'].to(device)
            label = D['label'].to(device).long()  # Ensure labels are integers

            optimizer.zero_grad()
            y_hat = model(image)  # Raw logits
            loss = criterion(y_hat, label)  # Cross-entropy loss
            loss.backward()
            optimizer.step()

            running_loss += loss.item()

        print(f"Epoch {epoch+1}, Loss: {running_loss/len(dataloader):.4f}")

    # Evaluation
    model.eval()
    outputs = []
    y_true = []

    with torch.no_grad():
        for D in dataloader:
            image = D['image'].to(device)
            label = D['label'].to(device).long()  # Ensure labels are integers

            y_hat = model(image)  # Raw logits

            outputs.append(y_hat.cpu().detach().numpy())
            y_true.append(label.cpu().detach().numpy())

    outputs = np.concatenate(outputs, axis=0)  # Shape: (N, num_classes)
    y_true = np.concatenate(y_true, axis=0).squeeze()  # Shape: (N,)

    # Predicted labels
    y_pred = predict_multiclass(outputs)

    # Accuracy, Precision, Recall, F1-Score
    accuracy = accuracy_score(y_true, y_pred)
    precision = precision_score(y_true, y_pred, average='weighted')  # Weighted for multiclass
    recall = recall_score(y_true, y_pred, average='weighted')        # Weighted for multiclass
    f1 = f1_score(y_true, y_pred, average='weighted')                # Weighted for multiclass

    print("Performance Metrics:")
    print(f"Accuracy: {accuracy:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall: {recall:.4f}")
    print(f"F1-Score: {f1:.4f}")

    # Confusion Matrix
    class_names = ['Class 1', 'Class 2', 'Class 3']
    plot_confusion_matrix(y_true, y_pred, class_names, title="Confusion Matrix")

# Debugging: Check unique values in y_true and y_pred
print("Unique values in y_true:", np.unique(y_true))
print("Unique values in y_pred:", np.unique(y_pred))